const express = require('express');
const { TokenCheckMiddleware } = require('../utils/middleware.js');
const router = express.Router();
const shopping_controller = require('../controllers/ShoppingController');
router.post('/add-to-cart',shopping_controller.addToCart);
router.post('/count_top',shopping_controller.countHelper);
router.get('/get-quantity/:user_id',TokenCheckMiddleware,shopping_controller.showItemCart);
router.get('/show-cart-view/:user_id',TokenCheckMiddleware,shopping_controller.showCartView);
router.post('/order',TokenCheckMiddleware,shopping_controller.placeOrder);
router.get('/show-order/:user_id',TokenCheckMiddleware,shopping_controller.showOrder);
router.delete('/delete-order',TokenCheckMiddleware,shopping_controller.deleteOrder);
module.exports = router;